# .github/workflows/ci-cd.yml
name: Full-Stack Authentication CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
    - name: Build Backend
      working-directory: ./backend
      run: npm run build

  frontend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

  docker-build:
    needs: [backend-test, frontend-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Compose
      run: docker-compose build
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Docker Hub
      run: |
        docker tag fullstack-auth-backend ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-auth-backend
        docker tag fullstack-auth-frontend ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-auth-frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-auth-backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-auth-frontend